name: Minifuzz Tests

on:
  push:
    branches: [ main ]
  pull_request:
      branches: [ main ]
  workflow_dispatch:
  repository_dispatch:
  schedule:
    # 8:00 AM Europe/Warsaw (6:00 UTC, using UTC+2 summer time)
    - cron: '0 6 * * *'
    # 12:00 PM Europe/Warsaw (10:00 UTC)
    - cron: '0 10 * * *'
    # 4:00 PM Europe/Warsaw (14:00 UTC)
    - cron: '0 14 * * *'
    # 8:00 PM Europe/Warsaw (18:00 UTC)
    - cron: '0 18 * * *'
    # Midnight Europe/Warsaw (22:00 UTC previous day)
    - cron: '0 22 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  init:
    name: Initializing environment
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Fetch Typeberry Docker image
        run: npm run fetch-typeberry
      - name: Build minifuzz
        run: npm run build -w minifuzz

  minifuzz:
    needs: init
    name: Minifuzz Tests
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        test: [burn, faulty, forks, no_forks]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run Minifuzz ${{ matrix.test }} test
        run: |
          npm exec tsx --test tests/minifuzz/${{ matrix.test }}.test.ts
