name: Picofuzz Tests

on:
  push:
    branches: [ main ]
  pull_request:
      branches: [ main ]
  workflow_dispatch:
  repository_dispatch:
  schedule:
    # 8:00 AM Europe/Warsaw (6:00 UTC, using UTC+2 summer time)
    - cron: '0 6 * * *'
    # 12:00 PM Europe/Warsaw (10:00 UTC)
    - cron: '0 10 * * *'
    # 4:00 PM Europe/Warsaw (14:00 UTC)
    - cron: '0 14 * * *'
    # 8:00 PM Europe/Warsaw (18:00 UTC)
    - cron: '0 18 * * *'
    # Midnight Europe/Warsaw (22:00 UTC previous day)
    - cron: '0 22 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  init:
    name: Initializing environment
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Fetch Typeberry Docker image
        run: npm run fetch-typeberry
      - name: Build picofuzz
        run: npm run build-docker -w @fluffylabs/picofuzz
      - name: Prepare test cases
        run: npm run prepare-data -w @fluffylabs/picofuzz
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: picofuzz-data
          path: ./picofuzz-data

  picofuzz:
    needs: init
    name: Picofuzz Test
    runs-on: [self-hosted, perf]
    strategy:
      fail-fast: false
      matrix:
        test: [fallback, safrole, storage, storage_light]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Download picofuzz-data
        uses: actions/download-artifact@v4
        with:
          name: picofuzz-data
          path: ./picofuzz-data

      - run: mkdir ./picofuzz-result && chmod 777 ./picofuzz-result

      - name: Download previous CSV files
        uses: actions/download-artifact@v4
        with:
          name: picofuzz-csv-${{ matrix.test }}
          path: ./picofuzz-result/
        continue-on-error: true

      - name: Run picofuzz ${{ matrix.test }}
        run: |
          npm exec tsx --test tests/picofuzz/${{ matrix.test }}.test.ts

      - name: Upload CSV results
        uses: actions/upload-artifact@v4
        with:
          name: picofuzz-csv-${{ matrix.test }}
          path: ./picofuzz-result/${{ matrix.test }}.csv
          retention-days: 90
        if: always()
